export const LOAD_POKEMONS = 'LOAD_POKEMONS';
export const POKEMONS_WAS_LOADED = 'POKEMONS_WAS_LOADED';
export const POKEMONS_LOADING_FAILED = 'POKEMONS_LOADING_FAILED';
export const LOAD_POKEMONS_BY_TYPE = 'LOAD_POKEMONS_BY_TYPE';
export const LOAD_POKEMON_BY_ID = 'LOAD_POKEMON_BY_ID';
export const POKEMON_LOADED = 'POKEMON_LOADED';

// Pagination
export const GO_TO_FIRST_PAGE = 'GO_TO_FIRST_PAGE';
export const GO_TO_LAST_PAGE = 'GO_TO_LAST_PAGE';
export const CHANGE_RANGE_UP = 'CHANGE_RANGE_UP';
export const CHANGE_RANGE_DOWN = 'CHANGE_RANGE_DOWN';
