export const LOAD_ALL_POKEMONS = 'LOAD_ALL_POKEMONS';
export const POKEMONS_WAS_LOADED = 'POKEMONS_WAS_LOADED';
export const POKEMONS_LOADING_FAILED = 'POKEMONS_LOADING_FAILED';
export const LOAD_POKEMONS_BY_TYPE = 'LOAD_POKEMONS_BY_TYPE';
export const LOAD_POKEMON_BY_ID = 'LOAD_POKEMON_BY_ID';
export const POKEMON_LOADED = 'POKEMON_LOADED';
